name=Fnd
version=1.5.0
author=Adri Chowdhury
maintainer=Adri Chowdhury
sentence=Library for multiplexing FND Displays.
paragraph=Supports upto 6 digit displays and both common anode and common cathode variants.
category=Display
url=https://github.com/DarkCat26/FND
architectures=*
includes=FND.h